### ISSUE TITLE
Time wrong for Pythia community meeting

### ISSUE THREAD

**Issue by clyne** [pangeo-data/pangeo.io#27]
The meeting time for the Pythia community meeting is incorrectly [listed](https://www.pangeo.io/meetings) as 1pm ET. It should be 12pm ET. Thanks!

Tagging @brian-rose for awareness

**Comment by brian-rose** [comment]
@jmunroe will try to get this fixed.

**Comment by clyne** [comment]
Thanks @maxrjones !
