### ISSUE TITLE
link to the meetings calendar?

### ISSUE THREAD

**Issue by keewis** [pangeo-data/pangeo.io#40]
I'm not sure if I didn't just miss it, but it looks like we don't link to the [meetings calendar](https://calendar.google.com/calendar/u/0/embed?src=ucar.edu_c23ln4014khs3f65o93vqv5kqc@group.calendar.google.com&ctz=America/Los_Angeles&pli=1) in the `meetings` page.

Should we change that?

**Comment by maxrjones** [comment]
I think this was just an oversight. I can open a PR to add it, or could review someone else's
