### ISSUE TITLE
Add Pangeo EGU sessions / short course as events

### ISSUE THREAD

**Issue by maxrjones** [pangeo-data/pangeo.io#53]
We have a new events page on the website - https://www.pangeo.io/events. It would be good to add the planned events at EGU2025 to this page:

Pangeo Session - ESSI2.15   https://meetingorganizer.copernicus.org/EGU25/session/52079 
Pangeo showcase: Geoscience using a Community Driven Approach 
Convener: Tina Odaka
Co-conveners: Anne Fouilloux, Alejandro Coca-Castro, Dean Summers, Ross A. W. Slater 

Pangeo short course - SC 4.14 
https://meetingorganizer.copernicus.org/EGU25/session/53638 
Harnessing the Power of Pangeo: Enhancing Your Scientific Data Analysis Workflow with scalable open source tools 
Convener: Anne Fouilloux
Co-conveners: Tina Odaka, Scott Henderson, Max Jones, Justus Magin 

FAIR & reusability ESSI3.2   https://meetingorganizer.copernicus.org/EGU25/session/52068 
One decade of FAIR Principles:  Data Reusability and Impact in Earth System Sciences 
Convener: Barbara Magagna
Co-conveners: Ivonne Anders, Karsten Peters-von Gehlen, Anne Fouilloux, Jie Dodo Xu 

This would be done by adding a new folder with the event id as the folder name in https://github.com/pangeo-data/pangeo.io/tree/main/src/events, and then adding an index.md file within that folder that contains the event information. The contents would be general markdown but would need the event metadata at the top as in https://raw.githubusercontent.com/pangeo-data/pangeo.io/refs/heads/main/src/events/agu-2024/index.md.

**Comment by ofk123** [comment]
Okay, thanks! Appreciate the advice and feedback @maxrjones. I will use a dev-branch for potential similar changes then, and open a request for these changes. Assuming it is too late to move it to a dev-branch?
