### ISSUE TITLE
Set the DNS record for Vercel deployment

### ISSUE THREAD

**Issue by maxrjones** [pangeo-data/pangeo.io#7]
The configuration for the domain is located at https://vercel.com/xarray/pangeo-io/settings/domains. We need to set the A Record and CNAME at the account at http://dns.he.net/ in order for this site to be deployed to the pangeo.io domain.

**Comment by maxrjones** [comment]
@jhamman would you be willing to update the DNS record for Pangeo, as someone who's both part of the Xarray Vercel team and HE account? Otherwise I'll ask to be added to the HE account, but I'd rather leave the DNS management to others. I would be super grateful for your help with this 😄

**Comment by jhamman** [comment]
I can definitely do this. Should be done in the next 24 hours.

**Comment by jhamman** [comment]
This is done now!

- https://pangeo.io/
- https://www.pangeo.io/

DNS is still updating so let me know if folks notice anything odd.
